version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: basic-crud
      POSTGRES_USER: root
      POSTGRES_PASSWORD: senha-postgres
    ports:
      - "5432:5432"